version: "3.9"

services:
  backend:
    build: ./backend
    container_name: readify-backend-dev
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PORT=${DB_PORT}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REDIS_URL=redis://host.docker.internal:6379
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
      - IMAGEKIT_URL_ENDPOINT=${IMAGEKIT_URL_ENDPOINT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - AI_API_KEY=${AI_API_KEY}
      - RESUME_PATH=${RESUME_PATH}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - GOOGLE_SHEET_ID=${GOOGLE_SHEET_ID}
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm start
    networks:
      - readify-network

networks:
  readify-network:
    driver: bridge
